Fixed the import resource line format. It was causing error on the server:
org.springframework.extensions.webscripts.WebScriptException: 04070005 Failed to load script 'classpath*:alfresco/site-webscripts/com/softwareloop/uploader-plus/uploader
/dnd-upload.get.js': 04070004 Malformed 'import' line - must be first in file, no comments and strictly of the form:
<import resource="...">

and

2015-05-07 14:31:51,374  ERROR [extensions.webscripts.AbstractRuntime] [http-bio-8080-exec-3] Exception from executeScript - redirecting to status template error: 04070003 Failed to load script 'classpath*:alfresco/site-webscripts/com/softwareloop/uploader-plus/uploader/flash-upload.get.js': 04070002 Malformed 'import' line - must be first in file, no comments and strictly of the form:^M
<import resource="...">